// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/wonderfate/ent-test-edges/ent/pet"
	"github.com/wonderfate/ent-test-edges/ent/schema"
	"github.com/wonderfate/ent-test-edges/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	petFields := schema.Pet{}.Fields()
	_ = petFields
	// petDescUserID is the schema descriptor for user_id field.
	petDescUserID := petFields[1].Descriptor()
	// pet.DefaultUserID holds the default value on creation for the user_id field.
	pet.DefaultUserID = petDescUserID.Default.(uint64)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescNickname is the schema descriptor for nickname field.
	userDescNickname := userFields[1].Descriptor()
	// user.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	user.NicknameValidator = userDescNickname.Validators[0].(func(string) error)
}
